image: docker:24.0.3-cli-alpine3.18

build:
  services:
    - docker:dind
  stage: build
  script:
    - apk add jq
    - apk add bash
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - bash update_and_build.sh



